version: '3.9'

services:
  db:
    ports:
      - '${DATABASE_PORT-5432}:5432'
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD-password}
      POSTGRES_USER: ${DATABASE_USERNAME-assignment}
      POSTGRES_DB: ${DATABASE_NAME-assignment}
    volumes:
      - db-assignment_data:/var/lib/postgresql/data
      # - ./docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    restart: always
    healthcheck:
      test: pg_isready -U assignment -d assignment
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  db-assignment_data:
    name: genie-assignment_data
